behaviors:
  OptimizeProduction:
    trainer_type: ppo
    time_horizon: 512
    max_steps: 1000000
    hyperparameters:
      learning_rate: 0.0001
      beta: 0.05
      epsilon: 0.3
    network_settings:
      hidden_units: 128
      num_layers:   2
      normalize: true
    reward_signals:
      extrinsic:
        gamma: 0.9975
        network_settings:
          hidden_units: 128
          num_layers:   2
          normalize: true